spring.application.name=GamesHubMobileBackend
server.port=8080

server.error.include-message=always
server.error.include-binding-errors=always  

logging.level.root=DEBUG

  # websocket
logging.level.org.springframework.web.socket=TRACE
logging.level.org.springframework.messaging=TRACE
logging.level.org.springframework.web.socket.messaging=TRACE

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

steam.api.key=55F2B85C22CB7C317465860792219889

spring.data.mongodb.uri=mongodb://localhost:27017/gamehub

stripe.api.key=${STRIPE_API_KEY}